services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./credentials:/app/credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/${GOOGLE_CREDENTIALS_FILE}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
      - RAG_DATABASE_HOST=http://chroma:8000
    env_file:
      - .env
    depends_on:
      - chroma
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma

volumes:
  chroma-data:
